#!/bin/bash

#arvu numbrite summa arvutamine

echo "Sisesta suvaline täisarv: "
read arv

summa=0

while [[ $arv -ne 0 ]]; do
jaak=$(( arv%10 ))
summa=$(( summa + jaak ))
arv=$(( ((arv - jaak)) / 10 ))
done

echo "Summa on $summa"

