#!/bin/bash

#paaris või paaritu, käsurealt

arv=$1

if [ $# -eq 0 ]; then
echo "Sa ei sisestanud midagi"
elif [ $# -ne 1 ]; then
echo "Sisestasid liiga palju argumente"
elif ! [[ $arv =~ ^[0-9]+$ ]]; then
echo "Sa ei sisestanud täisarvu"
elif [ $arv -eq 0 ]; then
echo "Sisestasid nulli"
elif [ $(($arv%2)) -ne 0 ]; then
echo "Antud arv on paaritu"
else
echo "Antud arv on paaris"
fi

